### ISSUE TITLE
Some global variable hashes are not being replaced properly

### ISSUE THREAD

**Issue by aboatcallie** [Scobalula/Cerberus-Repo#10]
![image](https://user-images.githubusercontent.com/30662495/61194256-f4d56e00-a685-11e9-975b-4f770b57cfd2.png)

Example variable: **level.var_75116c39**
Mapped definition in BlackOps3.txt: **0x75116c39**,**aat_in_use**
The proper variable replacement for **75116c39** is **aat_in_use**

The script in question is **scripts/zm/_zm_aat_blast_furnace.gsc**

The script was decompiled using the **CLI tool through a drag and drop operation**

[_zm_aat_blast_furnace.gsc.decompiled.txt](https://github.com/Scobalula/Cerberus-Repo/files/3390772/_zm_aat_blast_furnace.gsc.decompiled.txt)

**Comment by aboatcallie** [comment]
This issue did not occur when using the graphical interface

**Comment by Scobalula** [comment]
This issue was noted in a closed issue #7 and is fixed for an update that will available later today.
