### ISSUE TITLE
wont load any files, just stuck in idle

### ISSUE THREAD

**Issue by gauty40** [Scobalula/Cerberus-Repo#12]
i cant get any of the files to load, i try and drag and drop and it just does nothing, try to load them via the file explorer and it doesnt do anything

**Comment by Alexisloic21** [comment]
i thinks its because your file come from  momory exporting and not from fast file

**Comment by Scobalula** [comment]
Have you even checked the log?...

**Comment by gauty40** [comment]
> Have you even checked the log?...

i cant find a log anywhere?

**Comment by Scobalula** [comment]
![image](https://user-images.githubusercontent.com/12156105/61364713-49433e00-a87e-11e9-8b5d-2dec7d669a45.png)

**Comment by gauty40** [comment]
Loading hash tables
Loading BlackOps3.txt
Clearing Scripts
Scripts cleared
Loading D:\_keep\SteamLibrary\steamapps\common\Call of Duty Black Ops III\share\raw\scripts\zm\_ballistic_knife.gsc
Failed to load D:\_keep\SteamLibrary\steamapps\common\Call of Duty Black Ops III\share\raw\scripts\zm\_ballistic_knife.gsc
System.ArgumentException: Invalid Script Magic Number.
Parameter name: Magic
   at Cerberus.Logic.ScriptBase.LoadScript(BinaryReader reader, Dictionary`2 hashTables)
   at Cerberus.UI.MainWindow.LoadScriptFiles(String[] files)

**Comment by Scobalula** [comment]
You're attempting to load a source script, I don't know why you'd do that. Please read the instructions, etc.. This program is for people who know what they are doing.
