### ISSUE TITLE
Fix BO2 scripts decompiling as BO3 style scripts

### ISSUE THREAD

**Issue by Jbleezy** [Scobalula/Cerberus-Repo#14]
When I use BO2 scripts on this decompiler, it becomes a BO3 style script.

- Remove `function ` at the beginning of every function
- Change `#using` to `#include`
- Remove `#namespace`
- Change `&` to `::`
- Change `foreach` loops to `for` loops

**Comment by Scobalula** [comment]
As the tool is intended for use with Black Ops 3 Mod Tools I have no plans to target different versions of GSC syntax, it might be possible when I rewrite it at some point to do it, but not now. Also Bo2 and Bo1 support foreach.

**Comment by Jbleezy** [comment]
This should not be labeled as a Black Ops 2 decompiler then. That is very misleading.

Also, BO1 and BO2 most definitely do not support foreach.

**Comment by Scobalula** [comment]
Never scripted in Bo1 so honestly not 100% sure, but Bo2 100% does as that's what the generated while loops with _k, etc. are, there have also been source versions of bo2 scripts around that contain them.

You have the source code so any particular edits should be handled yourself. Locking convo as I'm not making these edits or getting into petty comments such as "misleading".
